---
- name: HTTPD Installation Playbook
  hosts: all
  remote_user: ansible
  become: yes  # Ensures sudo privileges for package installation
  roles:
    - httpd-installation
    - checking-directory-and-permission
    - copy-files
    - Configure-Firewall-and-Permissions
    - start-httpd