---
- name: installing packages for python env
  become: yes
  apt:
    name:
      - python3-pip
    update_cache: yes
    state: latest

- name: Creates directory
  file:
    path: /home/ansible/basic-http-server-new
    state: directory

- name: install apache2
  become: yes
  apt: name=apache2 update_cache=yes state=latest